### ISSUE TITLE
Website crash

### ISSUE THREAD

**Issue by gunar** [digitalbazaar/bitmunk#1]
[bitmunk.com](http://bitmunk.com/) gives

```
An error has occurred: {"code":"EHOSTUNREACH","errno":"EHOSTUNREACH","syscall":"connect"}
```

**Comment by davidlehn** [comment]
That's an error from a proxy probably because the site is down.  Or rather, the site that shows a message about the bitmunk.com being closed is down.  bitmunk.com itself has been shut off for a few years now.  Were you looking for something in particular?

**Comment by gunar** [comment]
@davidlehn Oh, uh... no, not really. I hadn't noticed this is an outdated project. Sorry to bother and thanks for the quick reply :)
